/// Held-out set v2: written after the last ontology adjustment and evaluated once, without
/// tuning on the result. This is the number quoted in docs/AI_ENGINE.md as the honest estimate.
const List<(String, String)> freshNotes = [
  ('Grab sourdough and cheddar on the way home', 'shopping|food'),
  ('Follow up on the knee MRI results', 'health'),
  ('Set up a monthly budget in a spreadsheet', 'finance'),
  ('Refactor the settings screen to use providers', 'tech'),
  ('The shower drain is clogged again', 'home'),
  ('Find a cheap hotel in Porto for the long weekend', 'travel'),
  ('Aperitivo with Chiara on Friday evening', 'people|food'),
  ('Review the German grammar flashcards', 'learning'),
  ('App concept: a shared shopping list that auto-sorts by supermarket aisle', 'ideas|tech'),
  ('Reserve a table at the new sushi place for Saturday', 'food'),
  ('Draft the Q3 performance review for Luca', 'work'),
  ('Booster shot appointment at the pharmacy next week', 'health'),
  ('Bolletta della luce da pagare entro fine mese', 'finance'),
  ("Chiamare l'idraulico per la perdita in bagno", 'home'),
  ('Comprare un regalo di compleanno per Paolo', 'shopping|people'),
  ('Studiare il capitolo sulla Rivoluzione francese', 'learning'),
  ("Pensare a un'idea per un podcast sulla cucina italiana", 'ideas|media'),
  ('Installare gli aggiornamenti e fare il backup del laptop', 'tech'),
  ('Pack the suitcase and check the boarding pass', 'travel'),
  ('Stretching and 30 minutes of yoga before bed', 'health'),
  ('Listen to the new episode of the Acquired podcast', 'media'),
  ('Order printer ink and a new HDMI cable', 'shopping|tech'),
  ('Anniversary dinner reservation on 14 November', 'people|food'),
  ('Sign the rental agreement and send it to the lawyer', 'admin'),
  ('Research standing desks and ergonomic chairs', 'shopping|home|health'),
  ('Water the plants and feed the cat', 'home'),
  ('Call grandma on Sunday', 'people'),
  ('Submit the expense report by Friday', 'work|finance'),
];
