/// Notes written *after* the ontology was tuned on `sampleCorpus`, never used to adjust it.
/// Accuracy on this list is the honest estimate of category quality (see docs/AI_ENGINE.md).
/// Alternatives are separated by `|` where a note genuinely sits between two domains.
const List<(String, String)> heldOutNotes = [
  ('Need oat milk, bananas and dish soap from the store', 'shopping|food'),
  ('Schedule a physical therapy session for my knee', 'health'),
  ('Transfer 200 euro to my savings account on Friday', 'finance'),
  ('Write unit tests for the payment module', 'tech'),
  ('Call the landlord about the broken heater', 'home'),
  ('Book train tickets Milan to Florence for the 14th', 'travel'),
  ('Sunday dinner with Marco and Giulia at 8pm', 'people|food'),
  ('Practice Spanish verbs for 20 minutes', 'learning'),
  ('Sketch logo ideas for the new brand', 'ideas'),
  ('Buy tickets for the Radiohead concert', 'media|shopping'),
  ("Prepare agenda for Thursday's team sync", 'work'),
  ('Renew car insurance before it expires', 'admin'),
  ('Cancel the gym membership', 'health|finance'),
  ('Try the new ramen place downtown', 'food'),
  ('I felt anxious all week, maybe too much coffee', 'health|personal'),
  ("Mom's birthday is on 3 November, order flowers", 'people|shopping'),
  ('Migrate the database to Postgres', 'tech'),
  ('Collect invoices and receipts for the tax return', 'finance|admin'),
  ('Walk the dog before work', 'home'),
  ("Chiedere il preventivo per l'apparecchio dal dentista", 'health'),
  ('Comprare detersivo e carta igienica', 'shopping'),
  ('Preparare la presentazione per il cliente di lunedì', 'work'),
  ('Prenotare il volo per Londra', 'travel'),
  ('Leggere il capitolo 4 del libro di storia', 'learning'),
  ('Pagare la bolletta del gas entro il 10 ottobre', 'finance'),
  ('Fix the typo on the landing page', 'tech|work'),
  ('Meditate 10 minutes every morning', 'health|personal'),
  ('Pizza night recipe: dough needs 24h to rise', 'food'),
  ('Watch the new Nolan movie this weekend', 'media'),
  ('Organize the garage and donate old clothes', 'home'),
];
