import '../text/text_utils.dart';

/// BERT-compatible WordPiece tokenizer (the tokenizer used by the bundled static model).
///
/// Mirrors Hugging Face `BertNormalizer` (clean text, pad CJK, strip accents, lower-case),
/// `BertPreTokenizer` (split on whitespace and punctuation) and `WordPiece` (greedy longest
/// match with a `##` continuation prefix; a word with any unmatched piece becomes `[UNK]`).
/// Token-id parity with the reference implementation is verified in
/// `test/static_encoder_test.dart` against fixtures generated by `tool/build_static_model.py`.
class WordPieceTokenizer {
  WordPieceTokenizer({
    required this.vocab,
    required this.unkId,
    this.continuingPrefix = '##',
    this.maxCharsPerWord = 100,
    this.lowercase = true,
    this.stripAccentsEnabled = true,
    this.handleChineseChars = true,
  });

  final Map<String, int> vocab;
  final int unkId;
  final String continuingPrefix;
  final int maxCharsPerWord;
  final bool lowercase;
  final bool stripAccentsEnabled;
  final bool handleChineseChars;

  /// Token ids for [text] (no special tokens). Unknown words yield [unkId].
  List<int> encode(String text) {
    final ids = <int>[];
    for (final word in _preTokenize(_normalize(text))) {
      _wordPiece(word, ids);
    }
    return ids;
  }

  /// Number of word pieces per word (an out-of-vocabulary word counts as one `[UNK]`).
  ///
  /// Words the model knows are a single piece; rare or invented words shatter into several
  /// fragments. [StaticTextEncoder.confidence] turns this into a reliability score.
  List<int> pieceCounts(String text) {
    final counts = <int>[];
    for (final word in _preTokenize(_normalize(text))) {
      final ids = <int>[];
      _wordPiece(word, ids);
      counts.add(ids.length);
    }
    return counts;
  }

  String _normalize(String text) {
    final sb = StringBuffer();
    for (final r in text.runes) {
      if (r == 0 || r == 0xFFFD || _isControl(r)) continue;
      if (_isWhitespace(r)) {
        sb.write(' ');
      } else if (handleChineseChars && _isCjk(r)) {
        sb
          ..write(' ')
          ..writeCharCode(r)
          ..write(' ');
      } else {
        sb.writeCharCode(r);
      }
    }
    final s = sb.toString();
    if (stripAccentsEnabled) return stripAccents(s); // also lower-cases
    return lowercase ? s.toLowerCase() : s;
  }

  List<String> _preTokenize(String s) {
    final words = <String>[];
    final cur = StringBuffer();
    void flush() {
      if (cur.isNotEmpty) {
        words.add(cur.toString());
        cur.clear();
      }
    }

    for (final r in s.runes) {
      if (r == 0x20) {
        flush();
      } else if (_isPunct(r)) {
        flush();
        words.add(String.fromCharCode(r));
      } else {
        cur.writeCharCode(r);
      }
    }
    flush();
    return words;
  }

  void _wordPiece(String word, List<int> out) {
    final chars = word.runes.toList(growable: false);
    if (chars.length > maxCharsPerWord) {
      out.add(unkId);
      return;
    }
    final pieces = <int>[];
    var start = 0;
    while (start < chars.length) {
      var end = chars.length;
      int? found;
      while (start < end) {
        var sub = String.fromCharCodes(chars, start, end);
        if (start > 0) sub = '$continuingPrefix$sub';
        final id = vocab[sub];
        if (id != null) {
          found = id;
          break;
        }
        end--;
      }
      if (found == null) {
        out.add(unkId);
        return;
      }
      pieces.add(found);
      start = end;
    }
    out.addAll(pieces);
  }

  static final RegExp _unicodePunct = RegExp(r'\p{P}', unicode: true);
  static final Map<int, bool> _punctCache = {};

  static bool _isPunct(int r) {
    if (r < 128) {
      return (r >= 33 && r <= 47) || (r >= 58 && r <= 64) || (r >= 91 && r <= 96) || (r >= 123 && r <= 126);
    }
    return _punctCache.putIfAbsent(r, () => _unicodePunct.hasMatch(String.fromCharCode(r)));
  }

  static bool _isWhitespace(int r) =>
      r == 0x20 ||
      (r >= 0x09 && r <= 0x0D) ||
      r == 0x85 ||
      r == 0xA0 ||
      r == 0x1680 ||
      (r >= 0x2000 && r <= 0x200A) ||
      r == 0x2028 ||
      r == 0x2029 ||
      r == 0x202F ||
      r == 0x205F ||
      r == 0x3000;

  static bool _isControl(int r) {
    if (r == 0x09 || r == 0x0A || r == 0x0D) return false;
    if (r < 0x20 || (r >= 0x7F && r <= 0x9F)) return true;
    // Common "format" (Cf) code points: soft hyphen, zero-width chars, bidi marks, BOM.
    return r == 0xAD ||
        (r >= 0x200B && r <= 0x200F) ||
        (r >= 0x202A && r <= 0x202E) ||
        (r >= 0x2060 && r <= 0x2064) ||
        (r >= 0x2066 && r <= 0x206F) ||
        r == 0xFEFF;
  }

  static bool _isCjk(int r) =>
      (r >= 0x4E00 && r <= 0x9FFF) ||
      (r >= 0x3400 && r <= 0x4DBF) ||
      (r >= 0x20000 && r <= 0x2A6DF) ||
      (r >= 0x2A700 && r <= 0x2B73F) ||
      (r >= 0x2B740 && r <= 0x2B81F) ||
      (r >= 0x2B820 && r <= 0x2CEAF) ||
      (r >= 0xF900 && r <= 0xFAFF) ||
      (r >= 0x2F800 && r <= 0x2FA1F);
}
